package view;

import java.awt.EventQueue;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;



public class signUp extends javax.swing.JPanel {

	private JFrame frame;

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					signUp window = new signUp();
					window.frame.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the application.
	 */
	

	/**
	 * Initialize the contents of the frame.
	 */
	private void initialize() {
		frame = new JFrame();
		frame.setBounds(100, 100, 450, 300);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	}
	
		
		/**
	     * Creates new form SignUpPanel
	     */
	    public signUp() {
			setBorder(null);
			setBackground(Color.WHITE);
	        initComponents();
			initialize();
			setVisible(true);


	    }

	    public JButton getBtSignUp() {
	        return btSignUp;
	    }

	    public JLabel getLbBack_signup() {
	        return lbBack_signup;
	    }

	    public JTextField getTfName() {
	        return tfName;
	    }

	    public JPasswordField getTfPass() {
	        return tfPass;
	    }

	    public JTextField getTfNom() {
	        return tfNom;
	    }
	    public JTextField getTfPrenom() {
	        return tfPrenom;
	    }
	    public JTextField getTfEmail() {
	        return tfEmail;
	    }


	
	    
	    public void clearTf() {
	        tfName.setText("");
	        tfPass.setText("");
	        tfNom.setText("");
	        tfPrenom.setText("");
	        tfEmail.setText("");


	        
	    }

	    
	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	    private void initComponents() {

	        jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        tfName = new javax.swing.JTextField();
	        jLabel4 = new javax.swing.JLabel();
	        jLabel5 = new javax.swing.JLabel();
	        tfPass = new javax.swing.JPasswordField();
	        tfNom = new javax.swing.JTextField();
	        tfPrenom = new javax.swing.JTextField();
	        tfEmail = new javax.swing.JTextField();
	        btSignUp = new javax.swing.JButton();
	        btSignUp.addActionListener(new ActionListener() {
	        	public void actionPerformed(ActionEvent e) {
	        	}
	        });
	        lbBack_signup = new javax.swing.JLabel();

	        jLabel1.setFont(new Font("Consolas", Font.BOLD, 36)); // NOI18N
	        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
	        jLabel1.setText("Sign up");

	        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
	        jLabel2.setText("Nom");

	        tfName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

	        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
	        jLabel4.setText("Username");

	        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
	        jLabel5.setText("Password");

	        tfPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

	        tfNom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

	        btSignUp.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
	        btSignUp.setForeground(new Color(51, 204, 51));
	        btSignUp.setText("Sign up");
	        btSignUp.setToolTipText("create new account");

	        lbBack_signup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
	        lbBack_signup.setToolTipText("Back");
	        
	        tfEmail.setFont(new Font("Tahoma", Font.PLAIN, 18));
	        
	        JLabel lblPrenom = new JLabel();
	        lblPrenom.setText("Prenom");
	        lblPrenom.setFont(new Font("Comic Sans MS", Font.PLAIN, 18));
	        
	        JLabel lblEmail = new JLabel();
	        lblEmail.setText("Email");
	        lblEmail.setFont(new Font("Comic Sans MS", Font.PLAIN, 18));
	        
	        JPanel panel = new JPanel();
	        panel.setBackground(new Color(51, 51, 204));
	        
	        tfPrenom.setFont(new Font("Tahoma", Font.PLAIN, 18));

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	        layout.setHorizontalGroup(
	        	layout.createParallelGroup(Alignment.LEADING)
	        		.addGroup(layout.createSequentialGroup()
	        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
	        				.addGroup(layout.createSequentialGroup()
	        					.addGap(76)
	        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
	        						.addComponent(lblPrenom, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
	        						.addComponent(jLabel2)
	        						.addComponent(lblEmail, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
	        						.addComponent(jLabel4, Alignment.TRAILING)
	        						.addGroup(layout.createSequentialGroup()
	        							.addComponent(jLabel5)
	        							.addPreferredGap(ComponentPlacement.RELATED))))
	        				.addGroup(layout.createSequentialGroup()
	        					.addGap(28)
	        					.addComponent(lbBack_signup)))
	        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
	        				.addGroup(layout.createSequentialGroup()
	        					.addGap(114)
	        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
	        						.addComponent(tfEmail, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)
	        						.addComponent(tfPass, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)
	        						.addComponent(tfName, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)
	        						.addComponent(tfNom, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)
	        						.addComponent(tfPrenom, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)))
	        				.addGroup(layout.createSequentialGroup()
	        					.addGap(141)
	        					.addComponent(jLabel1)))
	        			.addContainerGap(327, Short.MAX_VALUE))
	        		.addComponent(panel, GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
	        		.addGroup(layout.createSequentialGroup()
	        			.addGap(334)
	        			.addComponent(btSignUp)
	        			.addContainerGap(341, Short.MAX_VALUE))
	        );
	        layout.setVerticalGroup(
	        	layout.createParallelGroup(Alignment.LEADING)
	        		.addGroup(layout.createSequentialGroup()
	        			.addComponent(panel, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
	        			.addGap(21)
	        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
	        				.addGroup(layout.createSequentialGroup()
	        					.addComponent(jLabel1)
	        					.addGap(20)
	        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
	        						.addComponent(jLabel2)
	        						.addComponent(tfNom, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
	        					.addGap(18)
	        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
	        						.addComponent(lblPrenom)
	        						.addComponent(tfPrenom, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
	        					.addGap(15)
	        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
	        						.addComponent(lblEmail)
	        						.addComponent(tfEmail, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE))
	        					.addGap(19)
	        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
	        						.addComponent(jLabel4)
	        						.addComponent(tfName, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
	        					.addGap(19)
	        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
	        						.addComponent(jLabel5)
	        						.addComponent(tfPass, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
	        				.addComponent(lbBack_signup))
	        			.addGap(30)
	        			.addComponent(btSignUp)
	        			.addGap(78))
	        );
	        
	        txtpnEnsaChat = new JLabel();
	        txtpnEnsaChat.setText("ENSA CHAT");
	        txtpnEnsaChat.setForeground(Color.WHITE);
	        txtpnEnsaChat.setFont(new Font("Tahoma", Font.PLAIN, 21));
	        panel.add(txtpnEnsaChat);
	        this.setLayout(layout);
	    }// </editor-fold>//GEN-END:initComponents


	    // Variables declaration - do not modify//GEN-BEGIN:variables
	    private javax.swing.JButton btSignUp;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JLabel jLabel5;
	    private javax.swing.JLabel lbBack_signup;
	    private javax.swing.JTextField tfName;
	    private javax.swing.JPasswordField tfPass;
	    private javax.swing.JTextField  tfNom;
	    private javax.swing.JTextField  tfEmail;
	    private JLabel txtpnEnsaChat;
	    private JTextField tfPrenom;
	}



